=== Suyog311/GitDemo/QA_response_schema_030518.json
{
	"$schema": "http://json-schema.org/draft-04/schema#",
	"description": "QA API Response Schema",
	"$id": "http://example.com/example.json",
	"additionalProperties": false,
	"properties": 
	{
		"VerificationResponse": 
		{
			"type": "object",
			"additionalProperties": false,
			"properties": 
			{
				"vendor": 
				{
					"type": "string"
				},
				"submissionId": 
				{
					"type": "string"
				},
				"reports": 
				{
					"type": "object",
					"additionalProperties": false,
					"properties": 
					{
						"report": 
						{
							"type": "array",
							"items": 
							{
								"type": "object",
								"additionalProperties": false,
								"properties": 
								{
									"reportID": 
									{
										"type": "string"
									},
									"vendor": 
									{
										"type": "string"
									},
									"firstName": 
									{
										"type": "string"
									},
									"middleName": 
									{
										"type": "string"
									},
									"lastName": 
									{
										"type": "string"
									},
									"instApplId": 
									{
										"type": "string"
									},
									"SSN": 
									{
										"type": "string"
									}
								}
							}
						}
					}
				},
				"numBorrowers": 
				{
					"type": "string"
				},
				"attributedNetIncome": 
				{
					"type": "number"
				},
				"attributedGrossIncome": 
				{
					"type": "number"
				},
				"borrowerReportedIncome": 
				{
					"type": "number"
				},
				"applicants": 
				{
					"type": "object",
					"additionalProperties": false,
					"properties": 
					{
						"applicant": 
						{
							"type": "array",
							"items": 
							{
								"type": "object",
								"additionalProperties": false,
								"properties": 
								{
									"firstName": 
									{
										"type": "string"
									},
									"middleName": 
									{
										"type": "string"
									},
									"lastName": 
									{
										"type": "string"
									},
									"instApplId": 
									{
										"type": "string"
									},
									"SSN": 
									{
										"type": "string"
									},
									"wageIncomes": 
									{
										"type": "object",
										"additionalProperties": false,
										"properties": 
										{
											"wageIncome": 
											{
												"type": "array",
												"items": 
												{
													"type": "object",
													"additionalProperties": false,
													"properties": 
													{
														"incomeId": 
														{
															"type": "string"
														},
														"employerName": 
														{
															"type": "string"
														},
														"isSelfEmp": 
														{
															"type": "boolean"
														},
														"reportedBaseMonthlyIncome": 
														{
															"type": "number"
														},
														"reportedBonusMonthlyIncome": 
														{
															"type": "number"
														},
														"reportedOvertimeMonthlyIncome": 
														{
															"type": "number"
														},
														"reportedCommissionMonthlyIncome": 
														{
															"type": "number"
														},
														"attributedNetMonthlyIncome": 
														{
															"type": "number"
														},
														"attributedGrossMonthlyIncome": 
														{
															"type": "number"
														}
													}
												}
											}
										}
									},
									"nonWageIncomes": 
									{
										"type": "object",
										"additionalProperties": false,
										"properties": 
										{
											"nonWageIncome": 
											{
												"type": "array",
												"items": 
												{
													"type": "object",
													"additionalProperties": false,
													"properties": 
													{
														"incomeId": 
														{
															"type": "string"
														},
														"incomeType": 
														{
															"type": "string",
															"enum": 
															[
																"41",
																"42",
																"M4",
																"F1",
																"07",
																"F2",
																"F3",
																"02",
																"04",
																"03",
																"F4",
																"F5",
																"F6",
																"F7",
																"F8",
																"30",
																"F9",
																"AU",
																"M1",
																"M2",
																"M3",
																"NB",
																"45",
																"17",
																"SI",
																"S8",
																"33",
																"BI",
																"MC",
																"CG",
																"EA",
																"FI",
																"RP",
																"SE",
																"TL",
																"TI"
															]
														},
														"reportedMonthlyIncome": 
														{
															"type": "number"
														},
														"attributedNetMonthlyIncome": 
														{
															"type": "number"
														},
														"attributedGrossMonthlyIncome": 
														{
															"type": "number"
														}
													}
												}
											}
										}
									},
									"married": 
									{
										"type": "boolean"
									},
									"residencyState": 
									{
										"type": "string"
									}
								}
							}
						}
					}
				},
				"questions": 
				{
					"type": "object",
					"additionalProperties": false,
					"properties": 
					{
						"question": 
						{
							"type": "array",
							"items": 
							{
								"type": "object",
								"additionalProperties": false,
								"properties": 
								{
									"questionId": 
									{
										"type": "string"
									},
									"category": 
									{
										"type": "string",
										"enum": 
										[
											"applicant",
											"income_wage",
											"income_nonwage",
											"stream"
										]
									},
									"streamId": 
									{
										"type": "string"
									},
									"incomeId": 
									{
										"type": "string"
									},
									"instApplId": 
									{
										"type": "string"
									},
									"questionText": 
									{
										"type": "string"
									},
									"options": 
									{
										"type": "array",
										"items": 
										{
											"type": "object",
											"additionalProperties": false,
											"properties": 
											{
												"text": 
												{
													"type": "string"
												},
												"value": 
												{
													"type": "string"
												}
											}
										}
									},
									"answer": 
									{
										"type": "string"
									}
								}
							}
						}
					}
				},
				"streams": 
				{
					"type": "object",
					"additionalProperties": false,
					"properties": 
					{
						"stream": 
						{
							"type": "array",
							"items": 
							{
								"type": "object",
								"additionalProperties": false,
								"properties": 
								{
									"streamId": 
									{
										"type": "string"
									},
									"incomeId": 
									{
										"type": "string"
									},
									"incomeType": 
									{
										"type": "string"
									},
									"instApplId": 
									{
										"type": "string"
									},
									"accountKey": 
									{
										"type": "string"
									},
									"matchedApplName": 
									{
										"type": "string"
									},
									"minReq": 
									{
										"type": "string"
									},
									"missingLast": 
									{
										"type": "boolean"
									},
									"offDates": 
									{
										"type": "string"
									},
									"payFreq": 
									{
										"type": "string"
									},
									"regDeps": 
									{
										"type": "string"
									},
									"totDeps": 
									{
										"type": "string"
									},
									"unableToCalculate": 
									{
										"type": "boolean"
									},
									"omit": 
									{
										"type": "boolean"
									},
									"attributedNetMonthlyIncome": 
									{
										"type": "number"
									},
									"attributedGrossMonthlyIncome": 
									{
										"type": "number"
									},
									"empName": 
									{
										"type": "string"
									},
									"description": 
									{
										"type": "string"
									},
									"deposits": 
									{
										"type": "array",
										"items": 
										{
											"type": "object",
											"additionalProperties": false,
											"properties": 
											{
												"amount": 
												{
													"type": "string"
												},

												"date": 
												{
													"type": "string"
												},

												"offDate": 
												{
													"type": "boolean"
												},
												"rawMemo": 
												{
													"type": "string"
												},
												"seq": 
												{
													"type": "string"
												},
												"transactionId": 
												{
													"type": "string"
												}
											}
										}
									}
								}
							}
						}
					}
				},

				"messages": 
				{
					"type": "object",
					"additionalProperties": false,
					"properties": 
					{
						"message": 
						{
							"type": "array",
							"items": 
							{
								"type": "object",
								"additionalProperties": false,
								"properties": 
								{
									"msgId": 
									{
										"type": "string"
									},
									"msgCategory": 
									{
										"type": "string",
										"enum": 
										[
											"applicant",
											"income",
											"stream"
										]
									},
									"streamId": 
									{
										"type": "string"
									},
									"incomeId": 
									{
										"type": "string"
									},
									"instApplId": 
									{
										"type": "string"
									},
									"msgText": 
									{
										"type": "string"
									}
								}
							}
						}
					}
				}
			}
		},
		"Identity": 
		{
			"type": "string"
		},
		"ReportID": 
		{
			"type": "string"
		},
		"Product": 
		{
			"type": "string"
		},
		"TrackingKey": 
		{
			"type": "string"
		},
		"ServiceProviderCode": 
		{
			"type": "string"
		},
		"OriginalTransactionDate": 
		{
			"type": "string"
		},
		"Status": 
		{
			"type": "integer"
		},
		"Message": 
		{
			"type": "string"
		}
	}
}

=== Suyog311/GitDemo/QA_response_example_030518.json
{
	"VerificationResponse": 
	{
		"vendor": "Vendor Name",
		"submissionId": "0a4d55a8d778e5022fab701977c5d840bbc486d0",
		"numBorrowers": "1",
		"attributedNetIncome": 8621,
		"attributedGrossIncome": 8621,
		"borrowerReportedIncome": 10000,
		"reports": 
		{
			"report": 
			[
				{
					"reportID": "b1288058-2969-41aa-a2ee-64085c80faf7",
					"vendor": "report vendor",
					"firstName": "Patrick",
					"middleName": "",
					"lastName": "Purchaser",
					"instApplId": "1234",
					"SSN": "999-12-1234"
				}
			]
		},
		"applicants": 
		{
			"applicant": 
			[
				{
					"firstName": "Patrick",
					"middleName": "",
					"lastName": "Purchaser",
					"instApplId": "1234",
					"SSN": "999-12-1234",
					"wageIncomes": 
					{
						"wageIncome": 
						[
							{
								"incomeId": "0",
								"employerName": "ABC Employer",
								"isSelfEmp": false,
								"reportedBaseMonthlyIncome": 8000,
								"reportedBonusMonthlyIncome": 0,
								"reportedOvertimeMonthlyIncome": 0,
								"reportedCommissionMonthlyIncome": 0,
								"attributedNetMonthlyIncome": 5800,
								"attributedGrossMonthlyIncome": 7000
							}
						]
					},
					"nonWageIncomes": 
					{
						"nonWageIncome": 
						[
							{
								"incomeId": "1",
								"incomeType": "42",
								"reportedMonthlyIncome": 2000,
								"attributedNetMonthlyIncome": 1621,
								"attributedGrossMonthlyIncome": 1621
							}
						]
					},
					"married": true,
					"residencyState": "VA"
				}
			]
		},
		"questions": 
		{
			"question": 
			[
				{
					"category": "applicant",
					"streamId": "",
					"incomeId": "",
					"questionId": "1",
					"instApplId": "1234",
					"questionText": "'What is this applicant's marital status?",
					"options": 
					[
						{
							"text": "Married",
							"value": "M"
						},
						{
							"text": "Unmarried",
							"value": "U"
						}
					],
					"answer": "M"
				},
				{
					"category": "applicant",
					"streamId": "",
					"incomeId": "",
					"questionId": "2",
					"instApplId": "1234",
					"questionText": "'What is this applicant's state of residence?",
					"options": 
					[
						{
							"text": "Alabama",
							"value": "AL"
						},
						{
							"text": "Alaska",
							"value": "AK"
						},
						{
							"text": "Arizona",
							"value": "AZ"
						},
						{
							"text": "Arkansas",
							"value": "AR"
						},
						{
							"text": "California",
							"value": "CA"
						},
						{
							"text": "Colorado",
							"value": "CO"
						},
						{
							"text": "Connecticut",
							"value": "CT"
						},
						{
							"text": "Delaware",
							"value": "DE"
						},
						{
							"text": "District Of Columbia",
							"value": "DC"
						},
						{
							"text": "Florida",
							"value": "FL"
						},
						{
							"text": "Georgia",
							"value": "GA"
						},
						{
							"text": "Hawaii",
							"value": "HI"
						},
						{
							"text": "Idaho",
							"value": "ID"
						},
						{
							"text": "Illinois",
							"value": "IL"
						},
						{
							"text": "Indiana",
							"value": "IN"
						},
						{
							"text": "Iowa",
							"value": "IA"
						},
						{
							"text": "Kansas",
							"value": "KS"
						},
						{
							"text": "Kentucky",
							"value": "KY"
						},
						{
							"text": "Louisiana",
							"value": "LA"
						},
						{
							"text": "Maine",
							"value": "ME"
						},
						{
							"text": "Maryland",
							"value": "MD"
						},
						{
							"text": "Massachusetts",
							"value": "MA"
						},
						{
							"text": "Michigan",
							"value": "MI"
						},
						{
							"text": "Minnesota",
							"value": "MN"
						},
						{
							"text": "Mississippi",
							"value": "MS"
						},
						{
							"text": "Missouri",
							"value": "MO"
						},
						{
							"text": "Montana",
							"value": "MT"
						},
						{
							"text": "Nebraska",
							"value": "NE"
						},
						{
							"text": "Nevada",
							"value": "NV"
						},
						{
							"text": "New Hampshire",
							"value": "NH"
						},
						{
							"text": "New Jersey",
							"value": "NJ"
						},
						{
							"text": "New Mexico",
							"value": "NM"
						},
						{
							"text": "New York",
							"value": "NY"
						},
						{
							"text": "North Carolina",
							"value": "NC"
						},
						{
							"text": "North Dakota",
							"value": "ND"
						},
						{
							"text": "Ohio",
							"value": "OH"
						},
						{
							"text": "Oklahoma",
							"value": "OK"
						},
						{
							"text": "Oregon",
							"value": "OR"
						},
						{
							"text": "Pennsylvania",
							"value": "PA"
						},
						{
							"text": "Rhode Island",
							"value": "RI"
						},
						{
							"text": "South Carolina",
							"value": "SC"
						},
						{
							"text": "South Dakota",
							"value": "SD"
						},
						{
							"text": "Tennessee",
							"value": "TN"
						},
						{
							"text": "Texas",
							"value": "TX"
						},
						{
							"text": "Utah",
							"value": "UT"
						},
						{
							"text": "Vermont",
							"value": "VT"
						},
						{
							"text": "Virginia",
							"value": "VA"
						},
						{
							"text": "Washington",
							"value": "WA"
						},
						{
							"text": "West Virginia",
							"value": "WV"
						},
						{
							"text": "Wisconsin",
							"value": "WI"
						},
						{
							"text": "Wyoming",
							"value": "WY"
						}
					],
					"answer": "VA"
				},
				{
					"category": "income_wage",
					"streamId": "",
					"incomeId": "0",
					"questionId": "3",
					"instApplId": "1234",
					"questionText": "'Is this self-employment income?",
					"options": 
					[
						{
							"text": "Yes",
							"value": "Y"
						},
						{
							"text": "No",
							"value": "N"
						}
					],
					"answer": "N"
				},
				{
					"category": "income_wage",
					"streamId": "",
					"incomeId": "0",
					"questionId": "4",
					"instApplId": "1234",
					"questionText": "What is the monthly base income?",
					"options": 
					[
						
					],
					"answer": "8000"
				},
				{
					"category": "income_wage",
					"streamId": "",
					"incomeId": "0",
					"questionId": "5",
					"instApplId": "1234",
					"questionText": "What is the monthly bonus income?",
					"options": 
					[
						
					],
					"answer": "0"
				},
				{
					"category": "income_wage",
					"streamId": "",
					"incomeId": "0",
					"questionId": "6",
					"instApplId": "1234",
					"questionText": "What is the monthly overtime income?",
					"options": 
					[
		
					],
					"answer": "0"
				},
				{
					"category": "income_wage",
					"streamId": "",
					"incomeId": "0",
					"questionId": "7",
					"instApplId": "1234",
					"questionText": "What is the monthly comission income?",
					"options": 
					[
						
					],
					"answer": "0"
				},
				{
					"category": "income_wage",
					"streamId": "",
					"incomeId": "0",
					"questionId": "8",
					"instApplId": "1234",
					"questionText": "What is the employer name?",
					"options": 
					[
						
					],
					"answer": "ABC Employer"
				},
				{
					"category": "income_nonwage",
					"streamId": "",
					"incomeId": "1",
					"questionId": "9",
					"instApplId": "1234",
					"questionText": "What is the monthly income?",
					"options": 
					[
						
					],
					"answer": "0"
				},
				{
					"category": "stream",
					"streamId": "0",
					"incomeId": "",
					"questionId": "10",
					"instApplId": "",
					"questionText": "'Should this stream be omitted from consideration?",
					"options": 
					[
						{
							"text": "Yes",
							"value": "Y"
						},
						{
							"text": "No",
							"value": "N"
						}
					],
					"answer": "N"
				},
				{
					"category": "stream",
					"streamId": "0",
					"incomeId": "",
					"questionId": "11",
					"instApplId": "",
					"questionText": "'Which income source does this stream correspond to?",
					"options": 
					[
						{
							"text": "PATRICK PURCHASER WAGE: ABC Employer",
							"value": "0"
						},
						{
							"text": "PATRICK PURCHASER SOCIAL SECURITY",
							"value": "1"
						}
					],
					"answer": "0"
				},
				{
					"category": "stream",
					"streamId": "0",
					"incomeId": "",
					"questionId": "12",
					"instApplId": "",
					"questionText": "'What is the pay frequency of this pay stream?",
					"options": 
					[
						{
							"text": "Monthly",
							"value": "0"
						},
						{
							"text": "Semimonthly",
							"value": "1"
						},
						{
							"text": "Biweekly",
							"value": "2"
						},
						{
							"text": "Weekly",
							"value": "3"
						}
					],
					"answer": "0"
				},
				{
					"category": "stream",
					"streamId": "1",
					"incomeId": "",
					"questionId": "10",
					"instApplId": "",
					"questionText": "'Should this stream be omitted from consideration?",
					"options": 
					[
						{
							"text": "Yes",
							"value": "Y"
						},
						{
							"text": "No",
							"value": "N"
						}
					],
					"answer": "N"
				},
				{
					"category": "stream",
					"streamId": "1",
					"incomeId": "",
					"questionId": "11",
					"instApplId": "",
					"questionText": "'Which income source does this stream correspond to?",
					"options": 
					[
						{
							"text": "PATRICK PURCHASER WAGE: ABC Employer",
							"value": "0"
						},
						{
							"text": "PATRICK PURCHASER SOCIAL SECURITY",
							"value": "1"
						}
					],
					"answer": "1"
				},
				{
					"category": "stream",
					"streamId": "1",
					"incomeId": "",
					"questionId": "12",
					"instApplId": "",
					"questionText": "'What is the pay frequency of this pay stream?",
					"options": 
					[
						{
							"text": "Monthly",
							"value": "0"
						},
						{
							"text": "Semimonthly",
							"value": "1"
						},
						{
							"text": "Biweekly",
							"value": "2"
						},
						{
